stages:
  - build_and_push
  - deploy_to_kubernetes

build_and_push:
  image: docker:latest
  services: 
    - docker:dind
  stage: build_and_push
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker info
    - docker-compose build
  only:
    - master

deploy_to_kubernetes:
  image: kubectl:latest
  stage: deploy_to_kubernetes
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBE_CONFIG" | base64 -d > ~/.kube/config
  script:
    - kubectl apply -f gateway-service.yaml
  only:
    - master