stages:
  - build
  # - test
  - sonarqube

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  services:
    - docker:20.10-dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
    - docker-compose up -d --build
    - docker-compose ps

# test:
#   stage: test
#   script:
#     - docker-compose exec <service_name> pytest  # Replace <service_name> with your service name
#     - docker-compose down

sonarqube:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_HOST_URL: "http://localhost:9000"  # Replace with your SonarQube server URL
    SONAR_LOGIN: $SONAR_TOKEN  # Set this variable in GitLab CI/CD settings
  script:
    - sonar-scanner