stages:
  - build
  - deploy
  - sonarqube

variables:
  IMAGE_NAME: "mikeyspikey/ia-post-service"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  K8S_NAMESPACE: "default"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

before_script:
  - apk add --no-cache docker-compose

build:
  stage: build
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io

deploy:
  stage: deploy
  image:
    name: alpine/k8s:1.28.0
    entrypoint: ["/bin/sh", "-c"]
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - apk add --no-cache yq
    - mkdir -p $HOME/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > $HOME/.kube/config
    - export KUBECONFIG="$HOME/.kube/config"
  script:
    - echo "Deploying to Kubernetes cluster..."
    - kubectl apply -f .

# test:
#   stage: test
#   script:
#     - docker-compose exec <service_name> pytest  # Replace <service_name> with your service name
#     - docker-compose down

sonarqube:
  stage: sonarqube
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    SONAR_HOST_URL: "http://localhost:9000"  # Replace with your SonarQube server URL
    SONAR_LOGIN: $SONAR_TOKEN  # Set this variable in GitLab CI/CD settings
  script:
    - sonar-scanner