stages:
  - build_and_push
  - build_to_dockerhub
  - sonarqube
  - deploy

variables:
  IMAGE_NAME: "mikeyspikey/test"
  IMAGE_TAG: "$CI_COMMIT_SHA"
  K8S_NAMESPACE: "default"
  CI_PROJECT_NAME: "Libertas"
  SONAR_TOKEN: "sqp_e6678326772672d5ab4703f6c0d5377aaf284b03"
  DOCKER_TLS_CERTDIR: ""

build_and_push:
  stage: build_and_push
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker-compose build
    - docker compose push

build_to_dockerhub:
  stage: build_to_dockerhub
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
    - docker-compose build
    - docker compose push
  only:
    - master

sonarqube:
  stage: sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  allow_failure: true
  script:
    - sonar-scanner -Dsonar.projectKey=I431326_libertas_5e6a7ff3-81a8-42c4-b1bb-2252ede64057 -Dsonar.sources=. -Dsonar.host.url=http://sonarqube-custom:9000 -Dsonar.login=$SONAR_TOKEN

deploy:
  stage: deploy
  image: alpine/k8s:1.28.0
  before_script:
    - apk add --no-cache yq

    # Install secure files download tool
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash    
    # Make .kube directory and move config file    
    - mkdir ~/.kube    
    - mv .secure_files/config ~/.kube    
    - export KUBECONFIG=~/.kube/config

    - yq eval '(.clusters[] | select(.name == "docker-desktop").cluster.server) |= sub("127.0.0.1", "host.docker.internal")' -i ~/.kube/config

    - kubectl config get-contexts
  script:
    - kubectl config use-context docker-desktop
    - kubectl get nodes 
    - kubectl apply -f . -n $K8S_NAMESPACE
  environment:
    name: production