services:
  gateway:
    image: mikeyspikey/gateway:latest
    ports:
      - "8081:8081"
    volumes:
      - ./Gateway:/app
    command: npm start
  event-service:
    build:
      context: ./EventService
      dockerfile: Dockerfile
    image: mikeyspikey/event-service:latest
    volumes:
      - ./EventService:/app
    environment:
      NODE_ENV: development
      DB_HOST: event-database
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: events_db
    command: npm run dev
    depends_on:
      - gateway
      - rabbitmq
      - event-database
    deploy:
      replicas: 3
    ports:
      - "3001:3001"
  user-service:
      build:
        context: ./UserService
        dockerfile: Dockerfile
      image: mikeyspikey/user-service:latest
      volumes:
        - ./UserService:/app
      environment:
        NODE_ENV: development
        DB_HOST: user-database
        DB_USER: postgres
        DB_PASSWORD: mysecretpassword
        DB_NAME: users_db
      command: npm run dev
      depends_on:
        - gateway
        - rabbitmq
        - user-database
      deploy:
        replicas: 1
      ports:
        - "3003:3003"
  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    image: mikeyspikey/notification-service:latest
    volumes:
      - ./NotificationService:/app
    environment:
      NODE_ENV: development
      DB_HOST: notification-database
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: notifications_db
    command: npm run dev
    depends_on:
      - gateway
      - rabbitmq
      - notification-database
    deploy:
      replicas: 3
    ports:
      - "3002:3002"
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
  event-database:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: events_db
  notification-database:
    image: "postgres"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: notifications_db
  user-database:
      image: "postgres"
      ports:
        - "5434:5432"
      environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: users_db