apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\djmik\Desktop\Individueel\Libertas\Services\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: event-service
  name: event-service
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    io.kompose.service: event-service
