apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: event-database
  name: event-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-database
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: event-database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: events_db
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          image: postgres
          name: event-database
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
