apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: default
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: event-service
  type: ClusterIP