apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: event-service
  name: event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: event-service
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          env:
            - name: DB_HOST
              value: event-database
            - name: DB_NAME
              value: events_db
            - name: DB_PASSWORD
              value: mysecretpassword
            - name: DB_USER
              value: postgres
            - name: NODE_ENV
              value: development
          image: event-service
          name: event-service
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: event-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: event-service-cm0
          name: event-service-cm0
