apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mike-httproute
  namespace: default
spec:
  parentRefs:
  - name: mike-gateway
    namespace: gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/events"
      backendRefs:
      - name: event-service
        port: 3001
    - matches:
      - path:
          type: PathPrefix
          value: "/notifications"
      backendRefs:
      - name: notification-service
        port: 3002
    - matches:
      - path:
          type: PathPrefix
          value: "/SSE"
      backendRefs:
      - name: notification-service
        port: 3002
    - matches:
      - path:
          type: PathPrefix
          value: "/users"
      backendRefs:
      - name: user-service
        port: 3000