apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\djmik\Desktop\Individueel\Libertas\Services\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-database
  name: user-database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-database
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\djmik\Desktop\Individueel\Libertas\Services\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: users_db
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          image: postgres
          name: user-database
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
