apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\djmik\Desktop\Individueel\Libertas\Services\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\djmik\Desktop\Individueel\Libertas\Services\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - args:
            - npm
            - run
            - dev
          env:
            - name: DB_HOST
              value: user-database
            - name: DB_NAME
              value: users_db
            - name: DB_PASSWORD
              value: mysecretpassword
            - name: DB_USER
              value: postgres
            - name: NODE_ENV
              value: development
          image: mikeyspikey/user-service:latest
          name: user-service
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
