apiVersion: v1
kind: Service
metadata:
  name: event-service
spec:
  replicas: 1
  selector:
    app: event-service # Match the labels of your event service pods
  ports:
    - protocol: TCP
      port: 3001 # The port your event service listens on
      targetPort: 3001